// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250819171526_addNewClassesPayment")]
    partial class addNewClassesPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rachael Rutherford"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tyler Wolf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mike Cronin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jerry O'Kon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Derrick Parker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Travis Towne"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alonzo Murphy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kerry Weber"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nadine Braun"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ira Thompson"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jeannie Schneider"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Jenna Corkery"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Carroll Monahan"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Inez Brown"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Samuel Pfannerstill"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Lucy Greenfelder"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Isabel Douglas"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Eddie Cormier"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ollie Doyle"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Susie Marquardt"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Incredible Fresh Bike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Licensed Granite Bacon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Refined Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Small Frozen Towels"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sleek Steel Fish"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Handmade Wooden Fish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Incredible Soft Keyboard"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rustic Wooden Tuna"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Refined Soft Shirt"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Handmade Metal Keyboard"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fantastic Metal Soap"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Licensed Concrete Bike"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rustic Concrete Ball"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sleek Fresh Hat"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Refined Concrete Soap"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Practical Concrete Tuna"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Practical Rubber Sausages"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gorgeous Steel Chicken"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Licensed Steel Soap"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fantastic Concrete Gloves"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
