// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Andres Turcotte"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lynn Barrows"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andy Deckow"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pearl Powlowski"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jordan Labadie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Peter Keebler"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bessie Von"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shawn Gleason"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Meredith Hodkiewicz"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cathy Wolff"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Marty Wilderman"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hugo Rowe"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Essie Fisher"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Suzanne Ortiz"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Shaun Collins"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rudy Mayert"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lorene Padberg"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Felicia Johns"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Dale Streich"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Morris Quigley"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small Fresh Tuna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Metal Towels"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handmade Metal Chips"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Handcrafted Soft Soap"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rustic Concrete Tuna"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Handcrafted Concrete Chips"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Incredible Wooden Salad"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gorgeous Metal Towels"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Small Plastic Pants"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Incredible Plastic Sausages"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gorgeous Fresh Bacon"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Licensed Soft Gloves"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Intelligent Frozen Shirt"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Rustic Cotton Computer"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Intelligent Frozen Chips"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ergonomic Fresh Ball"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ergonomic Rubber Mouse"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gorgeous Steel Salad"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ergonomic Wooden Mouse"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sleek Cotton Table"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
